### PR TITLE
File rename

### PR DESCRIPTION
**Pull request by thayeylolu**

### CODE REVIEW

**Comment by Arushi282** [comment]
Could you change eda.py to maybe "correlation_eda.py"

**Comment by thayeylolu** [comment]
I think its fine as eda

**Comment by thayeylolu** [comment]
it looks too exposed as just `eda` 🤣

**Comment by karanpreetkaur** [comment]
Thanks @thayeylolu 

If you guys are all ok with the file rename , can I make changes in the make file for these ?

**Review by karanpreetkaur — APPROVED** [review]
Looks ok to me. Thanks @thayeylolu

**Comment by Arushi282** [comment]
> I think its fine as eda

I mean I would like to get @liannah 's opinion on this, I just think that the whole point of this exercise was to have more distinct file names for everything, and so it might be confusing to have the name "eda" for both ipynb and the script. Could be confusing also because of the fact that the script and the ipynb hold completely different plots.

**Comment by liannah** [comment]
> > I think its fine as eda
> 
> I mean I would like to get @liannah 's opinion on this, I just think that the whole point of this exercise was to have more distinct file names for everything, and so it might be confusing to have the name "eda" for both ipynb and the script. Could be confusing also because of the fact that the script and the ipynb hold completely different plots.

I agree with @Arushi282. I think eda should be only .ipynb file, and other name for .py file, as they represent two different things.  correlation_eda.py will work @thayeylolu @karanpreetkaur

**Comment by thayeylolu** [comment]
the

> > > I think its fine as eda
> > 
> > 
> > I mean I would like to get @liannah 's opinion on this, I just think that the whole point of this exercise was to have more distinct file names for everything, and so it might be confusing to have the name "eda" for both ipynb and the script. Could be confusing also because of the fact that the script and the ipynb hold completely different plots.
> 
> I agree with @Arushi282. I think eda should be only .ipynb file, and other name for .py file, as they represent two different things. correlation_eda.py will work @thayeylolu @karanpreetkaur

The difference between the two files is their file extension name. I`.py`  and `.ipynb` naming `.ipynb` correlation dea will imply we only did a correlation analysis in the notebook. Which we did not

**Pull request merged**
