### PR TITLE
Keeps Proposal

### PR DESCRIPTION
**Pull request by thayeylolu**

### CODE REVIEW

**Comment by liannah** [comment]
@thayeylolu what is this PR doing ? The commits are connected with script but the title is about proposal. Does it only create the md file ?

**Comment by Arushi282** [comment]
> @thayeylolu what is this PR doing ? The commits are connected with script but the title is about proposal. Does it only create the md file ?

Yeah I asked @thayeylolu to create a proposal md just to store our readme from the previous milestone. I think she made other other changes to the cleaning and preprocessing scripts as well. @thayeylolu please confirm this and let us know about the other changes you made, thanks!

**Comment by thayeylolu** [comment]
Yes, i created the the proposal as you mentioned. i believe i dont have changes to add

**Comment by thayeylolu** [comment]
but we can ignore it if we dont need it

**Comment by liannah** [comment]
> but we can ignore it if we dont need it

We need a proposal, I just wanted to know what where the commits about. I guess there was some confusion with commits history, but if this PR is creating md file then it is good to go. @thayeylolu @Arushi282

**Comment by liannah** [comment]
@thayeylolu After discussion we are cancelling this PR

**Pull request closed without merging**
