### PR TITLE
Added skeleton of EDA

### PR DESCRIPTION
**Pull request by liannah**

### CODE REVIEW

**Comment by thayeylolu** [comment]
@Lianna the `.ipynb` file should be in the `report` folder not in the `src`.

**Comment by Arushi282** [comment]
Hi @thayeylolu, no in the milestone 1 project example that tiffany has, the eda is in the src file, so lets just keep it that way.

**Comment by liannah** [comment]
Then what is our src file ? @thayeylolu I am writing the report inside ipynb as well as script

**Comment by Arushi282** [comment]
Just making sure you all know that we don't need scripts for the EDA, only for downloading the file, so we only the EDA jupyter notebook

**Pull request merged**
